apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
  namespace: data-network
  labels:
    app: iperf3-server
spec:
  nodeSelector:
    kubernetes.io/hostname: alvarolap
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: iperf3-slice1
    image: networkstatic/iperf3
    args: ["-s","-p","5201"]
    ports:
    - containerPort: 5201
  - name: iperf3-slice2
    image: networkstatic/iperf3
    args: ["-s","-p","5202"]
    ports:
    - containerPort: 5202
