apiVersion: v1
kind: Config
clusters:
- name: alvarolap-lab
  cluster:
    server: https://alvarolap.tailbd8454.ts.net:6443
    certificate-authority-data: XXXX
  user:
    token: XXXXX
- name: fiee-user@alvarolap-lab
  context:
    cluster: alvarolap-lab
    user: fiee-user
    namespace: open5gs
current-context: fiee-user@alvarolap-lab

